server:
  port: 8083
spring:
  application:
    name: alibaba-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  nacos-user-service: http://nacos-payment-provider



